name: automation

on:
  schedule:
    - cron:  '0 1 * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  scrape:
    name: scrape website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout data
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: 'repo'
          clean: true
      - name: prep env
        run: |
          sudo apt-get install -y libxml2-utils
          mkdir -p data
          cd repo
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Scrape data
        run: 'curl -sSL https://opensource.apple.com/source/apache/ | xmllint --html --xpath ''.//a[starts-with(@href,"apache")]/@href'' - | tr " " "\n" | sed -Ee ''s@href="apache-([^"]+)/"@\1@g'' | sort -u | grep -vf <(git -C repo tag | sed -Ee ''s/v(.*)/^\1$/g'' ) | xargs -I{} curl -o ./data/apache-{}.tgz "https://opensource.apple.com/tarballs/apache/apache-{}.tar.gz"'
      - name: loop and upload
        run: |
          for f in $(ls data/apache-* | sort -V); do
          mv $f ./
          gunzip apache-*.tgz
          tar -xf apache-*.tar
          rm apache-*.tar
          ver=$(ls -d apache-* | sed -Ee 's/apache-(.*)/\1/g' )
          pushd apache-${ver}
          mv ../repo/.git .
          mv ../repo/.github .
          rm -rf ../repo
          git add .
          git commit -m "Version ${ver}"
          git tag v${ver}
          git push origin
          git push origin --tags
          popd
          mv apache-${ver} repo
          done
